from django.core.management.base import BaseCommand
from core.models.technology_model import Technology

class Command(BaseCommand):
    help = 'Seed the technologies table with data'

    def handle(self, *args, **kwargs):
        technologies = [
            {'name': 'Python', 'level': 'beginner'},
            {'name': 'Python', 'level': 'intermediate'},
            {'name': 'Python', 'level': 'advanced'},
            {'name': 'C', 'level': 'beginner'},
            {'name': 'C', 'level': 'intermediate'},
            {'name': 'C', 'level': 'advanced'},
            {'name': 'C#', 'level': 'beginner'},
            {'name': 'C#', 'level': 'intermediate'},
            {'name': 'C#', 'level': 'advanced'},
            {'name': 'Ruby', 'level': 'beginner'},
            {'name': 'Ruby', 'level': 'intermediate'},
            {'name': 'Ruby', 'level': 'advanced'},
            {'name': 'Django', 'level': 'beginner'},
            {'name': 'Django', 'level': 'intermediate'},
            {'name': 'Django', 'level': 'advanced'},
            {'name': 'React', 'level': 'beginner'},
            {'name': 'React', 'level': 'intermediate'},
            {'name': 'React', 'level': 'advanced'},
            {'name': 'Angular', 'level': 'beginner'},
            {'name': 'Angular', 'level': 'intermediate'},
            {'name': 'Angular', 'level': 'advanced'},
            {'name': 'Node.js', 'level': 'beginner'},
            {'name': 'Node.js', 'level': 'intermediate'},
            {'name': 'Node.js', 'level': 'advanced'},
            {'name': 'JavaScript', 'level': 'beginner'},
            {'name': 'JavaScript', 'level': 'intermediate'},
            {'name': 'JavaScript', 'level': 'advanced'},
            {'name': 'TypeScript', 'level': 'beginner'},
            {'name': 'TypeScript', 'level': 'intermediate'},
            {'name': 'TypeScript', 'level': 'advanced'},
            {'name': 'HTML', 'level': 'beginner'},
            {'name': 'HTML', 'level': 'intermediate'},
            {'name': 'HTML', 'level': 'advanced'},
            {'name': 'CSS', 'level': 'beginner'},
            {'name': 'CSS', 'level': 'intermediate'},
            {'name': 'CSS', 'level': 'advanced'},
            {'name': 'Tailwind CSS', 'level': 'beginner'},
            {'name': 'Tailwind CSS', 'level': 'intermediate'},
            {'name': 'Tailwind CSS', 'level': 'advanced'},
            {'name': 'Bootstrap', 'level': 'beginner'},
            {'name': 'Bootstrap', 'level': 'intermediate'},
            {'name': 'Bootstrap', 'level': 'advanced'},
            {'name': 'Docker', 'level': 'beginner'},
            {'name': 'Docker', 'level': 'intermediate'},
            {'name': 'Docker', 'level': 'advanced'},
            {'name': 'Kubernetes', 'level': 'beginner'},
            {'name': 'Kubernetes', 'level': 'intermediate'},
            {'name': 'Kubernetes', 'level': 'advanced'},
            {'name': 'AWS', 'level': 'beginner'},
            {'name': 'AWS', 'level': 'intermediate'},
            {'name': 'AWS', 'level': 'advanced'},
            {'name': 'Google Cloud', 'level': 'beginner'},
            {'name': 'Google Cloud', 'level': 'intermediate'},
            {'name': 'Google Cloud', 'level': 'advanced'},
            {'name': 'MySQL', 'level': 'beginner'},
            {'name': 'MySQL', 'level': 'intermediate'},
            {'name': 'MySQL', 'level': 'advanced'},
            {'name': 'PostgreSQL', 'level': 'beginner'},
            {'name': 'PostgreSQL', 'level': 'intermediate'},
            {'name': 'PostgreSQL', 'level': 'advanced'},
            {'name': 'MongoDB', 'level': 'beginner'},
            {'name': 'MongoDB', 'level': 'intermediate'},
            {'name': 'MongoDB', 'level': 'advanced'},
            {'name': 'GraphQL', 'level': 'beginner'},
            {'name': 'GraphQL', 'level': 'intermediate'},
            {'name': 'GraphQL', 'level': 'advanced'},
            {'name': 'Redis', 'level': 'beginner'},
            {'name': 'Redis', 'level': 'intermediate'},
            {'name': 'Redis', 'level': 'advanced'},
            {'name': 'Git', 'level': 'beginner'},
            {'name': 'Git', 'level': 'intermediate'},
            {'name': 'Git', 'level': 'advanced'},
            {'name': 'GitHub', 'level': 'beginner'},
            {'name': 'GitHub', 'level': 'intermediate'},
            {'name': 'GitHub', 'level': 'advanced'},
        ]

        for tech in technologies:
            existing_tech = Technology.objects.filter(name=tech['name'], level=tech['level']).first()
            if not existing_tech:
                Technology.objects.create(**tech)

        self.stdout.write(self.style.SUCCESS('Successfully seeded the technologies table.'))